spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:mysql://database-1.c5wcjciz6aut.ap-northeast-2.rds.amazonaws.com:3306/articles?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: database

  mail:
    host: smtp.gmail.

    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: true


  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdidsfdsfdfsdfsdfsdfsdfsd

iamport:
  key: ${IAM_KEY}
  secret: ${IAM_SECRET}