spring:
  profiles:
    include: oauth
  #  sql:
  #    init:
  #      mode: always
  #  datasource:
  #    url: jdbc:h2:mem:testdb;
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC

  jpa:
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdidsfdsfdfsdfsdfsdfsdfsd